-- 共享菜品增量层（清单 C28 + C30）
--
-- 背景：303 道内置菜（data/dishes.js）在两个人的手机上各有一份且完全相同，不需要同步。
-- 对不齐的只有「有人在应用里加的菜」——那部分写各自手机的 wx storage。其中
--
--   干饭人加菜 → 掌勺人：已经通了（orders.items 是快照，菜名跟单过去；另有 dish_logs）
--   掌勺人加菜 → 干饭人：完全不通 —— 干饭人点单页读自己手机的菜单，看不到掌勺人加的菜
--
-- 这次补后面那一条：只有**掌勺人**的新增会进这张表，两台手机都合并进来。
--
-- 这张表原本是早期「菜单放云端」方案的残骸（101 行，代码零引用，见 C30）。
-- 结构本身（name / category / emoji / spice / description）正好够用，所以**保留并改造**，
-- 不做 DROP + CREATE —— 权限（GRANT + RLS）也已经配好了，重建反而要重配一遍。

-- ① 清掉残骸数据（101 行，与内置菜重复且过期；代码从未读过它）
TRUNCATE TABLE public.dishes;

-- ② id 交给数据库发号，从 100001 起。
--    这条是「两台手机不撞号」的关键：本地自增在两台手机上会从同一个数起步，
--    所以掌勺人新增的菜一律由云端发号，落在 constants.CLOUD_ID_BASE（100001）之后的
--    号段，与内置 seed 的 1..303 永久隔离。BY DEFAULT 允许显式插 id，便于将来回填。
ALTER TABLE public.dishes
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100001);

-- ③ 记「谁加的」（列表上可以标一句，日志 / 调试也看得到来源）
ALTER TABLE public.dishes
  ADD COLUMN IF NOT EXISTS by_name text NOT NULL DEFAULT '';

-- ④ 云端侧的最后修改时间。本机据此判断「云端这条是不是比我本地的新」，
--    也是客户端 mergeInto 里判定「真的变了」的依据之一。
ALTER TABLE public.dishes
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();

-- ⑤ 表注释改成它现在真正的职责（原来写的是「两个人共同维护的菜品库」，与事实不符）
COMMENT ON TABLE public.dishes IS
  '共享菜品增量层 · 只放掌勺人新增的菜（内置 303 道在 data/dishes.js 里，不进表）';

-- ⑥ identity 列的序列也要能被匿名 / 登录角色使用，否则 INSERT 会拿不到号。
--    （identity 列通常不需要单独授权，这里显式补上以免不同 PG 版本行为不一。）
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
